// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfeCyvendFN0Z9vJQztNo_bwhUT5VLPdY',
    appId: '1:1099133081143:android:bdc8c94209808976f0d1b2',
    messagingSenderId: '1099133081143',
    projectId: 'flutter-chat-app-3fd8d',
    storageBucket: 'flutter-chat-app-3fd8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE10HB2vTdtC63dISnnE-fKX8KfbZ5Im0',
    appId: '1:1099133081143:ios:905f2febbd51ac75f0d1b2',
    messagingSenderId: '1099133081143',
    projectId: 'flutter-chat-app-3fd8d',
    storageBucket: 'flutter-chat-app-3fd8d.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8cHr3QuKtO1W8SMe1zV5bZZfM3OHNtmo',
    appId: '1:1099133081143:web:f321f9e055c17f08f0d1b2',
    messagingSenderId: '1099133081143',
    projectId: 'flutter-chat-app-3fd8d',
    authDomain: 'flutter-chat-app-3fd8d.firebaseapp.com',
    storageBucket: 'flutter-chat-app-3fd8d.appspot.com',
  );

}